name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update yarn
        run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Check yarn version
        run: yarn --version

      - name: Install packages
        run: yarn install --immutable

      - name: Run npmluau
        run: yarn run prepare

      - name: Run linter
        run: yarn run lint

      - name: Verify code style
        run: yarn run style-check

      - name: Build assets
        run: yarn run build-assets
